---
kind: pipeline
type: docker
name: default

steps:
- name: verify
  image: alpine:3.18
  commands:
  - echo No verification step yet
- name: build
  image: alpine:3.18
  commands:
  - apk update
  - apk add zip
  - zip client.zip modlist.html manifest.json overrides/
  - ls
