---
kind: pipeline
type: docker
name: default

steps:
- name: verify_files
  image: alpine:3.18
  commands:
  - echo No verification step yet
- name: zip client
  image: alpine:3.18
  commands:
  - apk update
  - apk add zip
  - zip client.zip modlist.html manifest.json overrides/
