---
kind: pipeline
type: docker
name: default

steps:
- name: build client
  image: alpine:3.18
  commands:
  - apk update
  - apk add zip
  - mkdir dist
  - zip dist/client.zip client/modlist.html client/manifest.json client/overrides/
  - ls dist/
- name: discord notification
  image: appleboy/drone-discord
  settings:
    webhook_id:
      from_secret: discord_id
    webhook_token:
      from_secret: discord_secret
    message: >
      {{#success build.status}}
        ✅ Build {{build.number}} for {{repo.name}}/{{commit.branch}} succeeded.
      {{else}}
        ❌ Build {{build.number}} for {{repo.name}}/{{commit.branch}} failed.
      {{/success}}
  trigger:
    event:
      exclude:
      - pull_request
- name: publish release
  image: alpine:3.18
  commands:
  - echo todo
  trigger:
    event:
      include:
      - tag
      - promote
