---
kind: pipeline
type: docker
name: build

steps:
- name: build client
  image: alpine:3.18
  commands:
  - apk update
  - apk add zip
  - mkdir dist
  - zip dist/client.zip client/modlist.html client/manifest.json client/overrides/
  - ls dist/
- name: build server
  image: alpine:3.18
  commands:
  - echo test
- name: discord build notification
  image: appleboy/drone-discord
  settings:
    webhook_id:
      from_secret: discord_id
    webhook_token:
      from_secret: discord_secret
    message: >
      {{#success build.status}}
        ✅ Build {{build.number}} for {{repo.name}}/{{commit.branch}} succeeded
      {{else}}
        ❌ Build {{build.number}} for {{repo.name}}/{{commit.branch}} failed
      {{/success}}
  when:
    branch:
      exclude:
      - master
    event:
      exclude:
      - pull_request

---
kind: pipeline
type: docker
name: publish

steps:
- name: build client
  image: alpine:3.18
  commands:
  - apk update
  - apk add zip
  - mkdir dist
  - zip dist/serenity-custom_1.19.2-{{DRONE_TAG}}.zip client/modlist.html client/manifest.json client/overrides/
  - ls
- name: publish
  image: plugins/github-release
  settings:
    title: Release ${DRONE_TAG}
    api_key: xxxxxxxx
    files: dist/*
  when:
    event:
    - tag
- name: publish release
  image: alpine:3.18
  commands:
  - echo Releasing ${DRONE_TAG}
trigger:
  branch:
  - master
  event: 
  - tag
depends_on:
  - build