---
kind: pipeline
type: docker
name: default

steps:
- name: verify client
  image: alpine:3.18
  commands:
  - echo nothing yet
- name: build
  image: alpine:3.18
  commands:
  - apk update
  - apk add zip
  - zip client.zip modlist.html manifest.json overrides/
  - ls
- name: discord notification
  image: appleboy/drone-discord
  settings:
    webhook_id:
      from_secret: discord_id
    webhook_token:
      from_secret: discord_secret
    message: >
      {{#success build.status}}
        build {{build.number}} succeeded. Good job.
      {{else}}
        build {{build.number}} failed. Fix me please.
      {{/success}}
