---
kind: pipeline
type: docker
name: default

steps:
- name: verify client
  image: alpine:3.18
  commands:
  - test -e 32.jpg && return -1
- name: build
  image: alpine:3.18
  commands:
  - apk update
  - apk add zip
  - zip client.zip modlist.html manifest.json overrides/
  - ls
