version: 0.2

phases:
  build:
    commands:
      - echo Build started on $(date +%Y-%m-%d)
      - zip serenity.zip modlist.html manifest.json overrides/
  post_build:
    commands:
      - echo Build completed on $(date +%Y-%m-%d)
artifacts:
  files:
    - client.zip
